const TODOS_FILTER_ALL = `TODOS_FILTER_ALL`;
const TODOS_FILTER_COMPLITED = `TODOS_FILTER_COMPLITED`;
const TODOS_FILTER_PROGRESS = `TODOS_FILTER_PROGRESS`;

export {TODOS_FILTER_ALL, TODOS_FILTER_COMPLITED, TODOS_FILTER_PROGRESS};