const USERS_ALL_FILTER = `USERS_ALL_FILTER`;
const USERS_ACTIVE_FILTER = `USERS_ACTIVE_FILTER`;
const USERS_NON_ACTIVE_FILTER = `USERS_NON_ACTIVE_FILTER`;

export { USERS_ALL_FILTER, USERS_ACTIVE_FILTER, USERS_NON_ACTIVE_FILTER };
