const USER_ALL_FILTER = `USER_ALL_FILTER`;
const USER_ACTIVE_FILTER = `USER_ACTIVE_FILTER`;
const USER_NON_ACTIVE_FILTER = `USER_NON_ACTIVE_FILTER`;

export { USER_ALL_FILTER, USER_ACTIVE_FILTER, USER_NON_ACTIVE_FILTER };
